language: python
python:
- "2.5"
- "2.6"
# command to install dependencies
install:
- pip install . --use-mirrors
- pip install -r requirements.txt --use-mirrors
- pip install -r requirements-test.txt --use-mirrors
# command to run tests
script: nosetests #python setup.py test
