language: python
python:
- "2.5"
- "2.6"
- "2.7"
- "3.2"
- "pypy"
# command to install dependencies
install: pip install -r requirements.txt && pip install -r requirements-test.txt
# command to run tests
script: python setup.py test